name: ci-desafiojavapitang-workflow
on: [push]
jobs:
  check-application: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with: 
          java-version: 11
      - run: mvn test
