name: Desafio java Pitang CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Maven tests
        run: mvn test

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build docker image
        run: docker build -t luizcornelli/desafiojavapitang .

      - name: Push image docker
        run: docker push luizcornelli/desagiojavapitang:latest