name: Desafio java Pitang CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Maven tests
        run: mvn test

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Login Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t luizcornelli/desafiojavapitang .

      - name: Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: luizcornelli/desagiojavapitang:latest